apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mysqlpvc
spec:
  resources:
    requests:
      storage: 500Mi
  accessMode:
    - readWriteOnce
  storageClassName: mysqlStorageClass     