apiVersion: v1
kind: PersistentVolume
metadata: 
  name: mysqlpv
spec:
  storageClassName: mysqlstorageclass
  accessModes:
    - ReadWriteOnce
  capacity:
    storage: 1Gi     
  hostPath:
    path: /u01/data    