apiVersion: apps/v1
kind: Replicas
metadata:
  name: mysqlreplica
spec:
  replicas: 1  
  selector: 
    matchLabels:
      app: mysql
      version: "8.032"
  template:
    metadata: 
      name: mysqlpod
      labels:
        app: mysql
        version: "8.0.32"
  spec:
    containers:
      - name: mysqlcontainer
        image: mysql:8.0.32
        ports:
          - name: mysqlport
            containerPort: 3306
            protocol: TCP
        env:
          valueFrom:
            secretKeyRef:
              name: mysqlsecret
              key: password    
        volumeMount:
          name: mysqlvolume
          path: /var/lib/mysql       
    volume:
      name: mysqlvolume
      peristanceVolumeClaims: 
        claimName: mysqlStorageClass
